### ISSUE TITLE
Gathering System Configuration info Error + Database Access Scheme file error

### ISSUE THREAD

**Issue by catvsrat** [okoye/HA-OSCAR#21]
http://gist.github.com/264055

**Comment by catvsrat** [comment]
the installation was trying to initialize the database but could not access the scheme file.

**Comment by catvsrat** [comment]
After the  Gathering system configuration info installation started, i was asked to enter any other directories that may contain user data seperated by commas [e.g /data,/repos]:  i entered three inputs running the installation thrice.
1. empty path ( it says
-->  is  a valid directory[ies]?
-->  /home is a valid path
 2.-->  /SQ004981V02
-->  is /SQ004981V02 a valid directory[ies]?
-->  /home is a valid path
3.--> /home/catvsrat1/HA-OSCAR 
-->  is /home/catvsrat1/HA-OSCAR a valid directory[ies]?
-->  /home is a valid path
-->  /home/catvsrat1/HA-OSCAR is a valid path
 ,the third clearly mentioned that it was a valid path whereas the two above should also mentioned that the path was missing or incomplete or something ?

**Comment by okoye** [comment]
Not a bug.
