### ISSUE TITLE
Installation - creating authentication file

### ISSUE THREAD

**Issue by naratetaerat** [okoye/HA-OSCAR#22]
Command: haoscar_configure -m primary
(I was running as a root in Ubuntu 9.10)

Answering a few questions until the ha authentication, and I got this.

-->  creating authentication file
enter heartbeat authentication passwd: 
Traceback (most recent call last):
  File "./haoscar_configure", line 146, in <module>
    main()
  File "./haoscar_configure", line 109, in main
    if(heartbeat.configure() != 0):
  File "../halib/hatci/Heartbeat.py", line 53, in configure
    FILE = open(auth,"w+")
IOError: [Errno 2] No such file or directory: '/etc/ha.d/authkeys'

**Comment by okoye** [comment]
Is heartbeat already installed? If it is not, then this error will arise.

**Comment by naratetaerat** [comment]
heartbeat is not installed, but I thought system sanity check would tell me ... (but it said the system is sane)

**Comment by okoye** [comment]
Just created a new issue for system-sanity check ;)

**Comment by okoye** [comment]
Fixed!
