### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by naratetaerat** [okoye/HA-OSCAR#25]
System: Ubuntu 9.10 
Desc: I invoke haoscar_configure and immediately got the following messages 

Traceback (most recent call last):
  File "./haoscar_configure", line 32, in <module>
    import halib.hatci.Monit as monit
  File "../halib/hatci/Monit.py", line 24, in <module>
    import halib.hatci.monit.Apache as apache
ImportError: No module named monit.Apache

This is gotten worse dude :P

**Comment by okoye** [comment]
Forgot to run unit tests before pushing out. Will fix in next 2hrs.

**Comment by okoye** [comment]
Nope...nothing wrong with my branch...create a new repository. I think your pull from my repo went wrong.
